### ISSUE TITLE
Reserva de salas

### ISSUE THREAD

**Issue by maiconspa** [maiconspa/codando-discordbot#53]
## A ideia
Permitir que membros possam reservar de fato uma sala para determinados membros por um certo período de tempo

## Tasks
- [ ] Criar um cargo para cada sala (ex: Artemis-texto + Artemis-voz)
- [ ] Criar fluxo no Watson, coletar (data-horário inicial e final e membros permitidos na sala)
- [ ] Criar função (Function ou Lambda) para gerenciamento de cargos
- [ ] Somente o "host" (pessoa que agendou) poderá modificar o agendamento
- [ ] Possibilidade de prorrogar o tempo agendado
- [ ] Limitar quantidade de agendamentos

## Nice to have
- [ ] Lembrete mencionando o host sobre expiração de prazo de agendamento
